# WATER DEMAND FORECASTER

## Import Libraries

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load Dataset

In [19]:
df = pd.read_csv("urban_water_usage_dataset.csv")

In [20]:
df.head()

,date,water_usage,temperature,rainfall_mm,humidity_pct,population,is_festival,season
0,2012-05-21,165426914,35.1,4.9,55.0,1200000,0,Summer
1,2012-05-22,165253278,34.0,0.6,49.8,1200000,0,Summer
2,2012-05-23,161638528,32.9,2.1,45.2,1200000,0,Summer
3,2012-05-24,165292412,34.5,2.4,53.2,1200000,0,Summer
4,2012-05-25,171564211,36.9,1.7,49.8,1200000,0,Summer

## preeprocessing

In [ ]:
# convert date column to datetime
df['date'] = pd.to_datetime(df['date'])

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['dayofweek'] = df['date'].dt.dayofweek

In [22]:
df

,date,water_usage,temperature,rainfall_mm,humidity_pct,population,is_festival,season,year,month,day,dayofweek
0,2012-05-21,165426914,35.1,4.9,55.0,1200000,0,Summer,2012,5,21,0
1,2012-05-22,165253278,34.0,0.6,49.8,1200000,0,Summer,2012,5,22,1
2,2012-05-23,161638528,32.9,2.1,45.2,1200000,0,Summer,2012,5,23,2
3,2012-05-24,165292412,34.5,2.4,53.2,1200000,0,Summer,2012,5,24,3
4,2012-05-25,171564211,36.9,1.7,49.8,1200000,0,Summer,2012,5,25,4
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2026-01-23,139588612,23.5,1.4,54.7,1200000,0,Winter,2026,1,23,4
4996,2026-01-24,136000629,22.1,1.6,55.7,1200000,0,Winter,2026,1,24,5
4997,2026-01-25,134053248,21.3,1.6,57.3,1200000,0,Winter,2026,1,25,6
4998,2026-01-26,163894686,23.6,1.1,58.8,1200000,1,Winter,2026,1,26,0
4999,2026-01-27,151009074,28.0,0.2,65.0,1200000,0,Winter,2026,1,27,1

In [ ]:
# drop original date column
df.drop('date', axis=1, inplace=True)