# WATER DEMAND FORECASTER

## Import Libraries

In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load Dataset

In [96]:
df = pd.read_csv("urban_water_usage_dataset.csv")

In [97]:
df.head()

,date,water_usage,temperature,rainfall_mm,humidity_pct,population,is_festival,season
0,2012-05-21,165426914,35.1,4.9,55.0,1200000,0,Summer
1,2012-05-22,165253278,34.0,0.6,49.8,1200000,0,Summer
2,2012-05-23,161638528,32.9,2.1,45.2,1200000,0,Summer
3,2012-05-24,165292412,34.5,2.4,53.2,1200000,0,Summer
4,2012-05-25,171564211,36.9,1.7,49.8,1200000,0,Summer

## feature engineering

In [98]:
# convert date column to datetime
df['date'] = pd.to_datetime(df['date'])

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['dayofweek'] = df['date'].dt.dayofweek

In [99]:
df

,date,water_usage,temperature,rainfall_mm,humidity_pct,population,is_festival,season,year,month,day,dayofweek
0,2012-05-21,165426914,35.1,4.9,55.0,1200000,0,Summer,2012,5,21,0
1,2012-05-22,165253278,34.0,0.6,49.8,1200000,0,Summer,2012,5,22,1
2,2012-05-23,161638528,32.9,2.1,45.2,1200000,0,Summer,2012,5,23,2
3,2012-05-24,165292412,34.5,2.4,53.2,1200000,0,Summer,2012,5,24,3
4,2012-05-25,171564211,36.9,1.7,49.8,1200000,0,Summer,2012,5,25,4
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2026-01-23,139588612,23.5,1.4,54.7,1200000,0,Winter,2026,1,23,4
4996,2026-01-24,136000629,22.1,1.6,55.7,1200000,0,Winter,2026,1,24,5
4997,2026-01-25,134053248,21.3,1.6,57.3,1200000,0,Winter,2026,1,25,6
4998,2026-01-26,163894686,23.6,1.1,58.8,1200000,1,Winter,2026,1,26,0
4999,2026-01-27,151009074,28.0,0.2,65.0,1200000,0,Winter,2026,1,27,1

In [100]:
# drop original date column
df.drop('date', axis=1, inplace=True)

In [101]:
df.head()

,water_usage,temperature,rainfall_mm,humidity_pct,population,is_festival,season,year,month,day,dayofweek
0,165426914,35.1,4.9,55.0,1200000,0,Summer,2012,5,21,0
1,165253278,34.0,0.6,49.8,1200000,0,Summer,2012,5,22,1
2,161638528,32.9,2.1,45.2,1200000,0,Summer,2012,5,23,2
3,165292412,34.5,2.4,53.2,1200000,0,Summer,2012,5,24,3
4,171564211,36.9,1.7,49.8,1200000,0,Summer,2012,5,25,4

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   water_usage   5000 non-null   int64
 1   temperature   5000 non-null   float64
 2   rainfall_mm   5000 non-null   float64
 3   humidity_pct  5000 non-null   float64
 4   population    5000 non-null   int64
 5   is_festival   5000 non-null   int64
 6   season        5000 non-null   object
 7   year          5000 non-null   int32
 8   month         5000 non-null   int32
 9   day           5000 non-null   int32
 10  dayofweek     5000 non-null   int32
dtypes: float64(3), int32(4), int64(3), object(1)
memory usage: 351.7+ KB

In [103]:
df.isnull().sum()

water_usage     0
temperature     0
rainfall_mm     0
humidity_pct    0
population      0
is_festival     0
season          0
year            0
month           0
day             0
dayofweek       0
dtype: int64

## Define X and y

In [104]:
X = df.drop('water_usage', axis=1)
y = df['water_usage']

In [105]:
print(X)

      temperature  rainfall_mm  humidity_pct  population  is_festival  season  \
0            35.1          4.9          55.0     1200000            0  Summer
1            34.0          0.6          49.8     1200000            0  Summer
2            32.9          2.1          45.2     1200000            0  Summer
3            34.5          2.4          53.2     1200000            0  Summer
4            36.9          1.7          49.8     1200000            0  Summer
...           ...          ...           ...         ...          ...     ...
4995         23.5          1.4          54.7     1200000            0  Winter
4996         22.1          1.6          55.7     1200000            0  Winter
4997         21.3          1.6          57.3     1200000            0  Winter
4998         23.6          1.1          58.8     1200000            1  Winter
4999         28.0          0.2          65.0     1200000            0  Winter

      year  month  day  dayofweek
0     2012      5   21          0
1     2012      5   22          1
2     2012      5   23          2
3     2012      5   24          3
4     2012      5   25          4
...    ...    ...  ...        ...
4995  2026      1   23          4
4996  2026      1   24          5
4997  2026      1   25          6
4998  2026      1   26          0
4999  2026      1   27          1

[5000 rows x 10 columns]

In [106]:
print(y)

0       165426914
1       165253278
2       161638528
3       165292412
4       171564211
          ...
4995    139588612
4996    136000629
4997    134053248
4998    163894686
4999    151009074
Name: water_usage, Length: 5000, dtype: int64

## Label encoding

In [107]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X['season'] = le.fit_transform(X['season'])

## splitting the data in train and test

In [108]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [109]:
X_train

,temperature,rainfall_mm,humidity_pct,population,is_festival,season,year,month,day,dayofweek
4227,23.1,1.5,54.6,1200000,0,2,2023,12,17,6
4676,34.8,1.3,58.9,1200000,0,1,2025,3,10,0
800,28.2,6.1,73.0,1200000,0,0,2014,7,30,2
3671,29.3,2.3,76.9,1200000,0,0,2022,6,9,3
4193,22.8,0.7,63.6,1200000,0,2,2023,11,13,0
...,...,...,...,...,...,...,...,...,...,...
4426,26.6,4.0,78.4,1200000,0,0,2024,7,3,2
466,29.4,3.1,73.9,1200000,0,0,2013,8,30,4
3092,20.5,0.0,63.1,1200000,0,2,2020,11,7,5
3772,31.7,14.1,91.0,1200000,0,0,2022,9,18,6
860,30.4,16.9,73.5,1200000,0,0,2014,9,28,6

In [110]:
X_test

,temperature,rainfall_mm,humidity_pct,population,is_festival,season,year,month,day,dayofweek
1501,29.2,5.5,69.8,1200000,0,0,2016,6,30,3
2586,24.2,23.2,72.7,1200000,0,0,2019,6,20,3
2653,26.2,19.1,71.8,1200000,0,0,2019,8,26,0
1055,33.3,2.0,41.0,1200000,0,1,2015,4,11,5
705,33.1,0.4,49.2,1200000,0,1,2014,4,26,5
...,...,...,...,...,...,...,...,...,...,...
4711,34.5,1.2,47.8,1200000,0,1,2025,4,14,0
2313,30.1,5.7,72.6,1200000,0,0,2018,9,20,3
3214,37.8,14.0,44.5,1200000,0,1,2021,3,9,1
2732,19.5,7.6,59.9,1200000,0,2,2019,11,13,2
1926,30.3,25.7,69.8,1200000,0,0,2017,8,29,1

In [111]:
y_train

4227    138563226
4676    166816511
800     148052969
3671    152884412
4193    138210906
          ...
4426    145512777
466     152708807
3092    133258250
3772    151601739
860     146753151
Name: water_usage, Length: 4000, dtype: int64

In [112]:
y_test

1501    150844982
2586    128260806
2653    135515444
1055    162826116
705     163268846
          ...
4711    166103379
2313    152803176
3214    166457685
2732    126223045
1926    141315506
Name: water_usage, Length: 1000, dtype: int64

## feature scalling

In [113]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

## MODEL TRAIN + EVALUATION

In [114]:
## LINEAR REGRESSION

from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [122]:
# # RANDOM FORSET
# from sklearn.ensemble import RandomForestRegressor

# rf_model = RandomForestRegressor(
#     n_estimators=200,
#     random_state=42
# )


# rf_model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)
# y_pred_rf = rf_model.predict(X_test)

In [117]:
from sklearn.metrics import r2_score,mean_squared_error

r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("R2 Score:", r2)
print("RMSE:", rmse)

R2 Score: 0.9999730036515916
RMSE: 70543.87002398266

In [123]:
# r2_rf = r2_score(y_test, y_pred_rf)
# rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))

# print("Random Forest R2 Score:", r2_rf)
# print("Random Forest RMSE:", rmse_rf)



# Selected Linear Regression as final model for deployment; retained Random Forest for comparison

## save the model

In [124]:
import joblib

joblib.dump(model, "water_usage_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Model and scaler saved successfully")

Model and scaler saved successfully